### ISSUE TITLE
Image not updating when next question button selected

### ISSUE THREAD

**Issue by timcoghlan** [dominikwilkowski/bronzies#31] opened 2019-10-17 21:51 UTC
Hey Dom. Just noticed that the image is not changing when the next question button is selected next to the answer you just selected. using chrome

**Comment by dominikwilkowski** [comment] 2019-10-18 04:20
Hey @timcoghlan 

I can't reproduce this. Can you give me more infos how this happened for you?

**Comment by dominikwilkowski** [comment] 2020-01-18 00:37
I'll close this issue for now. Please re-open if you encounter it again or if you have more infos.

Cheers

**Closed by dominikwilkowski** 2020-01-18 00:37 UTC
Labels: question
